### ISSUE TITLE
Help: Use a GitHub Release as source

### ISSUE THREAD

**Issue by vromero** [openSUSE/obs-service-tar_scm#215]
I'm trying to use a file published in a GitHub [release](https://help.github.com/articles/creating-releases/).
All information I can find is around checking out the repository and compile/package from there. I would love to use an actual release because:

- recompile would just be unnecessary as the artifact uploaded to the release is not architecture dependent (java's jar)
-  the artifact is already signed in a safe environment (and I don't want to upload the private key anywhere else).

Is there any documentation/example that I could use as a start point?

**Comment by aspiers** [comment]
Hrm.  IIUC a GitHub release can either be just effectively a simple git tag, or it can also include extra files which are manually uploaded as release artifacts, and you are talking about the latter case - right?

If so, I think this source service is not the right choice, and a correct approach would be to use the `download_url` source service to download release artifact files directly from GitHub rather than relying on `git`.  Or if you're building rpms, you should go one step further and put those URLs directly in your `.spec` file as `SourceN:` headers, and use the `download_files` source service to retrieve them.  Here is [some documentation for how to use source services](http://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.source_service.html) although if you want to know about the details of individual source services, I don't personally know any better way than to [search for packages starting with `obs-service-`](https://software.opensuse.org/search?utf8=%E2%9C%93&q=obs-service&search_devel=false&search_unsupported=false&baseproject=openSUSE%3ALeap%3A42.2), then install the ones you're interested in, and look at the `.service` files under `/usr/lib/obs/service`.

Hopefully that provides what you need, but if not let me know and I can reopen.

**Comment by vromero** [comment]
Yes, you are right I'm talking about the files attached to a release. I was thinking about an _automatic_ mechanism to fetch them as they are released (just like a new Git rev is commited with tar_scm).
SourceN definitely works but it requires extra steps.
Thanks

**Comment by aspiers** [comment]
Right.  I think a new GitHub source service would have to be written for that; it's definitely beyond the scope of this one.
